import type { Category } from "./types"

export const categories: Category[] = [
  {
    id: "tous",
    label: "Tous",
    color: "#22C55E",
    gradient: "linear-gradient(160deg, #0A0A0B 0%, #0A0A0B 100%)",
    title: "Annuaire des incubateurs français",
    subtitle: "361 programmes indexés — filtrez, comparez, candidatez.",
    filterKey: "",
    filterValues: [],
  },
  {
    id: "corporate",
    label: "Corporate",
    color: "#6366F1",
    gradient: "linear-gradient(160deg, #0D0B1F 0%, #0A0A0B 100%)",
    title: "Incubateurs Corporate & Grands Groupes",
    subtitle: "Programmes internes CAC40, CVCs et structures corporate.",
    filterKey: "source",
    filterValues: ["Corporate", "Corporate Pharma", "Corporate Tech"],
  },
  {
    id: "ecoles",
    label: "Écoles",
    color: "#EC4899",
    gradient: "linear-gradient(160deg, #1A0B1C 0%, #0A0A0B 100%)",
    title: "Incubateurs des Grandes Écoles",
    subtitle: "HEC, Polytechnique, emlyon, ESSEC — les réseaux alumni actifs.",
    filterKey: "typeStructure",
    filterValues: ["Incubateur"],
  },
  {
    id: "public",
    label: "Public",
    color: "#3B82F6",
    gradient: "linear-gradient(160deg, #0A1628 0%, #0A0A0B 100%)",
    title: "Structures Publiques & Territoriales",
    subtitle: "BPI, régions, métropoles — financements non-dilutifs prioritaires.",
    filterKey: "source",
    filterValues: ["Open Data IDF", "Pôle compétitivité"],
  },
  {
    id: "pharma",
    label: "Pharma/Santé",
    color: "#14B8A6",
    gradient: "linear-gradient(160deg, #011F1E 0%, #0A0A0B 100%)",
    title: "Incubateurs Santé & Biotech",
    subtitle: "Medtech, biotech, e-santé — les hubs spécialisés.",
    filterKey: "secteur",
    filterValues: ["HealthTech"],
  },
  {
    id: "tech",
    label: "Tech/IA",
    color: "#8B5CF6",
    gradient: "linear-gradient(160deg, #1A0B35 0%, #0A0A0B 100%)",
    title: "Incubateurs Tech & Intelligence Artificielle",
    subtitle: "SaaS, deep tech, IA générative — les structures qui comprennent votre stack.",
    filterKey: "secteur",
    filterValues: ["Numérique/Tech", "DeepTech"],
  },
  {
    id: "impact",
    label: "Impact",
    color: "#22C55E",
    gradient: "linear-gradient(160deg, #041A10 0%, #0A0A0B 100%)",
    title: "Incubateurs Impact & Greentech",
    subtitle: "B-Corp, ESS, transition écologique — mission first.",
    filterKey: "secteur",
    filterValues: ["Impact Social", "GreenTech"],
  },
  {
    id: "reseaux",
    label: "Réseaux",
    color: "#F59E0B",
    gradient: "linear-gradient(160deg, #1C1203 0%, #0A0A0B 100%)",
    title: "Réseaux d'Entraide & Prêts d'Honneur",
    subtitle: "Réseau Entreprendre, Initiative France — financement + mentoring bénévole.",
    filterKey: "source",
    filterValues: ["Réseau accompagnement"],
  },
]
