import type { Category } from "./types"

export const categories: Category[] = [
  {
    id: "tous",
    label: "Tous",
    color: "#22C55E",
    gradient: "linear-gradient(160deg, #0A0A0B 0%, #0A0A0B 100%)",
    title: "Annuaire des incubateurs français",
    subtitle: "+550 programmes référencés — filtrez, comparez, candidatez.",
    filterKey: "",
    filterValues: [],
  },
  {
    id: "incubateurs",
    label: "Incubateurs",
    color: "#22C55E",
    gradient: "linear-gradient(160deg, #041A10 0%, #0A0A0B 100%)",
    title: "Incubateurs",
    subtitle: "Programmes d'accompagnement long — de l'idée au produit.",
    filterKey: "typeStructure",
    filterValues: ["Incubateur"],
  },
  {
    id: "accelerateurs",
    label: "Accélérateurs",
    color: "#8B5CF6",
    gradient: "linear-gradient(160deg, #1A0B35 0%, #0A0A0B 100%)",
    title: "Accélérateurs",
    subtitle: "Programmes intensifs et courts — scaler vite.",
    filterKey: "typeStructure",
    filterValues: ["Accélérateur"],
  },
  {
    id: "corporate",
    label: "Corporate",
    color: "#6366F1",
    gradient: "linear-gradient(160deg, #0D0B1F 0%, #0A0A0B 100%)",
    title: "Incubateurs Corporate & Grands Groupes",
    subtitle: "Programmes internes CAC40, CVCs et structures corporate.",
    filterKey: "source",
    filterValues: ["Corporate", "Corporate Pharma", "Corporate Tech"],
  },
  {
    id: "ecoles",
    label: "Écoles",
    color: "#EC4899",
    gradient: "linear-gradient(160deg, #1A0B1C 0%, #0A0A0B 100%)",
    title: "Incubateurs des Grandes Écoles",
    subtitle: "HEC, Polytechnique, emlyon, ESSEC — les réseaux alumni actifs.",
    filterKey: "alumniNotables",
    filterValues: ["école", "École", "HEC", "ESSEC", "ESCP", "emlyon", "Centrale", "Polytechnique", "Dauphine", "Sciences Po", "SKEMA", "KEDGE", "NEOMA", "EDHEC", "IÉSEG", "BSB", "INSEEC", "IMT", "Télécom", "Arts et Métiers", "EFREI", "ENSCI"],
  },
  {
    id: "public",
    label: "Public",
    color: "#3B82F6",
    gradient: "linear-gradient(160deg, #0A1628 0%, #0A0A0B 100%)",
    title: "Structures Publiques & Territoriales",
    subtitle: "BPI, régions, métropoles, CCI — financements non-dilutifs.",
    filterKey: "source",
    filterValues: ["Open Data IDF", "Pôle compétitivité"],
  },
  {
    id: "studios",
    label: "Startup Studios",
    color: "#F59E0B",
    gradient: "linear-gradient(160deg, #1C1203 0%, #0A0A0B 100%)",
    title: "Startup Studios",
    subtitle: "Co-construction de startups — ils buildent avec vous.",
    filterKey: "typeStructure",
    filterValues: ["Startup Studio"],
  },
  {
    id: "reseaux",
    label: "Réseaux",
    color: "#14B8A6",
    gradient: "linear-gradient(160deg, #011F1E 0%, #0A0A0B 100%)",
    title: "Réseaux d'Entraide & Prêts d'Honneur",
    subtitle: "Réseau Entreprendre, Initiative France — financement + mentoring bénévole.",
    filterKey: "source",
    filterValues: ["Réseau accompagnement"],
  },
]
