import type { Incubator } from "./types"

export const FALLBACK_DATA: Incubator[] = [
  {
    nom: "Founders Program @ Station F",
    alumniNotables: "Plus grand campus de startups au monde",
    linkedin: "https://www.linkedin.com/company/station-f/",
    region: "Île-de-France",
    secteur: "Généraliste",
    siteWeb: "https://stationf.co/programs/founders",
    ville: "Paris",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Accélérateur",
    dureeMois: "3-18",
    coutEur: "259€/desk/mois",
    equityPct: "1",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Bureau", "Mentorat", "Réseau"],
    themesDetailles: "",
    departement: "75",
    adresse: "5 parvis Alan Turing",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Agoranov",
    alumniNotables: "Doctolib, Alan, LegalStart — 540+ entreprises",
    linkedin: "https://www.linkedin.com/company/agoranov/",
    region: "Île-de-France",
    secteur: "DeepTech",
    siteWeb: "https://www.agoranov.com",
    ville: "Paris",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Incubateur",
    dureeMois: "6-24",
    coutEur: "",
    equityPct: "0",
    profilFounder: ["Chercheur"],
    techNonTech: "Tech",
    avantages: ["Mentorat", "Réseau", "Financement"],
    themesDetailles: "",
    departement: "75",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Wilco",
    alumniNotables: "50+ exits — fort track record",
    linkedin: "https://www.linkedin.com/company/wilco-vc/",
    region: "Île-de-France",
    secteur: "Généraliste",
    siteWeb: "https://www.wilco.vc",
    ville: "Paris",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Accélérateur",
    dureeMois: "6-12",
    coutEur: "0",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Mentorat", "Financement", "Réseau"],
    themesDetailles: "",
    departement: "75",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Incubateur HEC Paris",
    alumniNotables: "400+ startups incubées",
    linkedin: "https://www.linkedin.com/company/incubateur-hec-paris/",
    region: "Île-de-France",
    secteur: "Généraliste",
    siteWeb: "https://builders.hec.fr/incubateur",
    ville: "Jouy-en-Josas",
    stadeAccepte: ["Idéation", "Pré-seed"],
    typeStructure: "Incubateur",
    dureeMois: "3-24",
    coutEur: "250€/bureau/mois",
    equityPct: "0",
    profilFounder: ["Étudiant"],
    techNonTech: "Les deux",
    avantages: ["Bureau", "Mentorat", "Réseau"],
    themesDetailles: "",
    departement: "78",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "21st by CentraleSupélec",
    alumniNotables: "Accélère l'impact pour entrepreneurs visionnaires",
    linkedin: "https://www.linkedin.com/showcase/21st-accelerateur/",
    region: "Île-de-France",
    secteur: "DeepTech",
    siteWeb: "https://21st.centralesupelec.com/",
    ville: "Gif-sur-Yvette",
    stadeAccepte: ["Idéation", "Pré-seed", "Seed"],
    typeStructure: "Accélérateur",
    dureeMois: "",
    coutEur: "400€/mois",
    equityPct: "",
    profilFounder: ["Étudiant", "Chercheur"],
    techNonTech: "Tech",
    avantages: ["Bureau", "Mentorat", "Financement"],
    themesDetailles: "",
    departement: "91",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "EuraTechnologies",
    alumniNotables: "Plus grand incubateur européen — 300+ entreprises",
    linkedin: "https://www.linkedin.com/company/euratechnologies/",
    region: "Hauts-de-France",
    secteur: "Numérique/Tech",
    siteWeb: "https://www.euratechnologies.com",
    ville: "Lille",
    stadeAccepte: ["Idéation", "Pré-seed"],
    typeStructure: "Incubateur",
    dureeMois: "6",
    coutEur: "",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Tech",
    avantages: ["Bureau", "Mentorat", "Réseau"],
    themesDetailles: "",
    departement: "59",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "H7 Lyon",
    alumniNotables: "Plus grand incubateur lyonnais",
    linkedin: "https://www.linkedin.com/company/h7lyon/",
    region: "Auvergne-Rhône-Alpes",
    secteur: "Généraliste",
    siteWeb: "https://h-7.eu/",
    ville: "Lyon",
    stadeAccepte: ["Pré-seed", "Seed", "Growth"],
    typeStructure: "Accélérateur",
    dureeMois: "12-36",
    coutEur: "",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Tech",
    avantages: ["Bureau", "Mentorat", "Réseau"],
    themesDetailles: "",
    departement: "69",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "50 Partners",
    alumniNotables: "200+ startups accélérées",
    linkedin: "https://www.linkedin.com/company/50-partners/",
    region: "Île-de-France",
    secteur: "Numérique/Tech",
    siteWeb: "https://www.50partners.fr/",
    ville: "Paris",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Accélérateur",
    dureeMois: "",
    coutEur: "0",
    equityPct: "7",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Bureau", "Mentorat", "Financement", "Réseau"],
    themesDetailles: "",
    departement: "75",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Paris&Co",
    alumniNotables: "1000 investisseurs engagés, 100+ experts",
    linkedin: "https://www.linkedin.com/company/paris&co/",
    region: "Île-de-France",
    secteur: "Impact Social",
    siteWeb: "https://www.parisandco.paris",
    ville: "Paris",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Incubateur",
    dureeMois: "12",
    coutEur: "12000€/an",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Bureau", "Mentorat", "Financement", "Réseau"],
    themesDetailles: "",
    departement: "75",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Nubbo",
    alumniNotables: "Incubateur à mission — impact social",
    linkedin: "https://www.linkedin.com/company/nubbo/",
    region: "Occitanie",
    secteur: "Impact Social",
    siteWeb: "https://www.nubbo.fr",
    ville: "Toulouse",
    stadeAccepte: ["Idéation", "Pré-seed"],
    typeStructure: "Incubateur",
    dureeMois: "12-20",
    coutEur: "0",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Mentorat", "Financement", "Réseau"],
    themesDetailles: "",
    departement: "31",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Village by CA",
    alumniNotables: "40+ villages en France",
    linkedin: "https://www.linkedin.com/company/le-village-by-ca/",
    region: "Partout en France",
    secteur: "Généraliste",
    siteWeb: "https://levillagebyca.com",
    ville: "",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Incubateur",
    dureeMois: "12-24",
    coutEur: "",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Bureau", "Mentorat", "Réseau"],
    themesDetailles: "",
    departement: "",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Réseau Entreprendre",
    alumniNotables: "Prêts d'honneur 15-50K€, 350+ implantations",
    linkedin: "",
    region: "Partout en France",
    secteur: "Généraliste",
    siteWeb: "https://www.reseau-entreprendre.org/",
    ville: "",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Réseau",
    dureeMois: "24",
    coutEur: "0",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Mentorat", "Financement", "Réseau"],
    themesDetailles: "",
    departement: "",
    adresse: "",
    actif: true,
    source: "Réseau accompagnement",
  },
  {
    nom: "Initiative France",
    alumniNotables: "1er réseau associatif financement créateurs",
    linkedin: "",
    region: "Partout en France",
    secteur: "Généraliste",
    siteWeb: "https://www.initiative-france.fr/",
    ville: "",
    stadeAccepte: ["Idéation", "Pré-seed", "Seed"],
    typeStructure: "Réseau",
    dureeMois: "",
    coutEur: "0",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Financement", "Mentorat", "Réseau"],
    themesDetailles: "",
    departement: "",
    adresse: "",
    actif: true,
    source: "Réseau accompagnement",
  },
  {
    nom: "Platform58",
    alumniNotables: "Incubateur La Banque Postale — Fintech/AssurTech",
    linkedin: "https://www.linkedin.com/company/platform58-incubateur/",
    region: "Île-de-France",
    secteur: "Finance/AssurTech",
    siteWeb: "https://www.platform58.labanquepostale.fr/",
    ville: "Paris",
    stadeAccepte: ["Pré-seed", "Seed"],
    typeStructure: "Incubateur",
    dureeMois: "12",
    coutEur: "0",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Tech",
    avantages: ["Bureau", "Mentorat", "Réseau", "Crédits cloud"],
    themesDetailles: "",
    departement: "75",
    adresse: "",
    actif: true,
    source: "Notion",
  },
  {
    nom: "Willa",
    alumniNotables: "1er accélérateur diversité tech — 1000+ startups",
    linkedin: "https://www.linkedin.com/company/willa-off/",
    region: "Île-de-France",
    secteur: "Féminin",
    siteWeb: "https://hellowilla.co/",
    ville: "Paris",
    stadeAccepte: ["Idéation", "Pré-seed", "Seed"],
    typeStructure: "Incubateur",
    dureeMois: "6-18",
    coutEur: "",
    equityPct: "0",
    profilFounder: ["Tous"],
    techNonTech: "Les deux",
    avantages: ["Bureau", "Mentorat", "Réseau"],
    themesDetailles: "",
    departement: "75",
    adresse: "",
    actif: true,
    source: "Notion",
  },
]
